config/routes.rb
Rails.application.routes.draw do
  resources :jobs
  root 'jobs#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :jobs
end

app/models/job.rb
class Job < ApplicationRecord
	include HTTParty
	include Nokogiri

	belongs_to :category

	attr_reader :category_parser

	def self.scraper(cat_type=nil)
		url = "https://miami.craigslist.org/search/sof"
		if cat_type.present?
			@options = { query: {
					employment_type: Job.category_parser(cat_type)
				}
			}
		end
		response = HTTParty.get(url, (@options.presence || {}))
		dom = Nokogiri::HTML(response.body)
		return dom.css("a.hdrlnk")
	end

	private
		def self.category_parser(cat_type)
			case cat_type
			when "Full-Time"
				return 1
			when "Part-Time"
				return 2
			when "Contract"
				return 3
			when "Employee's Choice"
				return 4
			else
				return 1
			end
		end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController

	before_action :find_job, only: [:show, :edit, :update, :destroy]


	def index
		@craig_jobs = Job.scraper(params[:category].presence)

		if params[:category].blank?
			@jobs = Job.all.order("created_at DESC")
		else
			@category_id = Category.find_by(name: params[:category]).id
			@jobs = Job.where(category_id: @category_id).order("created_at DESC")
		end
	end

	def show
	end

	def new
		@job = Job.new
	end

	def create
		@job = Job.new(jobs_params)

		if @job.save
			redirect_to @job
		else
			render "new"
		end
	end

	def edit
	end

	def update
		if @job.update(jobs_params)
			redirect_to @job
		else
			render "edit_job"
		end
	end

	def destroy
		@job.destroy
		redirect_to root_path
	end

	private
	def jobs_params
		params.require(:job).permit(:title, :description, :company, :url, :category_id)
	end

	def find_job
		@job = Job.find(params[:id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/jobs/_form.html.haml
- if @job.errors.any?
	%h2= pluralize(@job.errors.count, "error") + "prohibited this job from being saved"
	- @job.errors.full_messages.each do |msg|
		%li= msg
= simple_form_for(@job, html: { class: 'form-horizontal'}) do |f|
	= f.collection_select :category_id, Category.all, :id, :name, {prompt: "Choose Category"}, input_html: { class: "dropdown-toggle" }
	= f.input :title, label: "Job Title", input_html: { class: "form-control" }
	= f.input :description, label: "Job Description", input_html: { class: "form-control" }
	= f.input :company, label: "Your Company", input_html: { class: "form-control" }
	= f.input :url, label:  "Link to Job", input_html: { class: "form-control" }
	%br/
	= f.button :submit

app/views/jobs/edit.html.haml
%h1 Edit Job

= render "form"

= link_to "Back", root_path

app/views/jobs/index.html.haml
#jobs
	- @jobs.each do |job|
		.job
			%h2= link_to job.title.titleize, job.url, target: "_blank"

#jobs
	- @craig_jobs.each do |job|
		.job
			%h2= link_to job.text.titleize, job['href'], target: "_blank"

app/views/jobs/new.html.haml
%h1 New Job

= render "form"

= link_to "Back", root_path

app/views/jobs/show.html.haml
#jobs
  .job
  %h2= @job.title
  %p= @job.description
  %p= @job.company
  %button.btn.btn-default= link_to "Apply for Job", @job.url

#link
  = link_to "Back", root_path, class: "btn btn-sm btn-default"
  = link_to "Edit", edit_job_path(@job), class: "btn btn-sm btn-default"
  = link_to "Delete", job_path(@job), method: :delete, data: {confirm:  "Are you sure?"}, class: "btn btn-sm btn-default"

app/views/layouts/application.html.haml
%html
%head
  %title Ruby on Dev Job
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
  = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  = csrf_meta_tags
%body
  %nav.navbar.navbar-default
    .container
      .navbar-brand Dev Jobs
      %ul.nav.navbar-nav
        %li= link_to "All Jobs", root_path
        -Category.all.each do |category|
          %li= link_to category.name, jobs_path(category: category.name)
      = link_to "New Job", new_job_path, class: "navbar-text navbar-right navbar-link"
  .container
    .col-md-6.col-md-offset-3
      = yield

app/views/layouts/show.html.haml
%h1= @job.title
%p= @job.description
%p= @job.company

= link_to "Home", root_path
= link_to "Edit", edit_job_path(@job)
= link_to "Delete", job_path(@job), method: :delete, data: { confirm: "Are you sure?"}